pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
                sh 'git clone https://github.com/ezepsuarez/aplicacion-devops.git || true'
                sh 'cd aplicacion-devops && sudo git checkout unidad-2-app'
                sh 'cd aplicacion-devops/ && sudo /usr/local/bin/composer install --no-scripts'
                sh ' ls -l ./aplicacion-devops/bootstrap/'
                sh 'sudo chmod 777 -R ./aplicacion-devops/bootstrap/'
            }
        }
        stage('Build') {
            steps {
                sh 'find . -path ./aplicacion-devops/vendor -prune -o -name \\*.php -exec php -l "{}" \\;'
                retry(2) {
                    //sh 'cd aplicacion-devops && sudo /usr/local/bin/composer update --no-scripts --prefer-dist'
                    sh 'cd aplicacion-devops && /usr/local/bin/composer create-project aplicacion-devops sample-app --prefer-dist'
                }
            }
        }
        stage('Test') {
            steps {
                sh './aplicacion-devops/vendor/bin/phpunit -c ./aplicacion-devops/phpunit.xml'
            }
        }
    }
}
